toonvanstrijp/nestjs-i18n

LICENCE.md
package.json

add a licence file and label to the `package.json` file

add licence

---

src/lib/index.ts
src/lib/resolvers/cookie.resolver.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n-gql.e2e.spec.ts

Added another tests also for cookie resolver and added a fix

fixed CookieResolver and added more tests

---

package-lock.json
src/lib/i18n.context.ts

Made I18nContext.detectedLanguage public

---

README.md

I read through the documentation of this repo and found some typos.
I fixed them in this PR

Corrected some typos in README.md

---

README.md

While setting up the package in my project I came upon another small error in the readme

Correction in README.md

---

README.md
package-lock.json
package.json
src/lib/index.ts
src/lib/middleware/i18n-language-middleware.ts
src/lib/resolvers/accept-language.resolver.ts
src/lib/resolvers/header.resolver.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n-gql.e2e.spec.ts

Resolves #99 #64 
- Added AcceptLanguageResolver
- Added dependency `accept-language-parser`
- Removed dependency `accept-language-negotiator`. It wasn't used anywhere but still included in package.json
- Modified README.me

Adding AcceptLanguageResolver

---

src/services/i18n.service.ts
tests/app/controllers/hello.controller.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n/en/test.json
tests/i18n/nl/test.json

issue: https://github.com/ToonvanStrijp/nestjs-i18n/issues/205

fix nested translation

---

src/services/i18n-request-scope.service.ts

fix: #223 I18nRequestScopeService with gRPC

---

package.json
src/i18n.module.ts
src/services/i18n.service.ts
tests/app/controllers/hello.controller.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n/en/test.json
tests/i18n/fr/test.json
tests/i18n/nl/test.json
tests/i18n/pt-BR/test.json

fix nested translations without args

---

src/i18n.context.ts
src/services/i18n-request-scope.service.ts
src/services/i18n.service.ts
tests/app/controllers/hello.controller.ts

Return Generic Type in Translate Methods

---

package-lock.json
package.json
src/i18n.module.ts
src/interfaces/i18n-options.interface.ts
tests/app/views/ejs/index.ejs
tests/app/views/ejs/index2.ejs
tests/i18n-ejs.e2e.spec.ts

template(ejs): add ejs support

---

docs/concepts/loader.md
docs/concepts/resolver.md
docs/guides/dto-validation.md
package-lock.json
package.json
src/filters/i18n-validation-exception.filter.ts
src/interfaces/i18n-validation-error.interface.ts
tests/app/controllers/hello.controller.ts
tests/i18n-dto.e2e.spec.ts

This PR adds doc for  missing loaders, resolvers and also updates the i18nExceptionErrorFilter for the previous simplified error message

doc: add doc for resolver,loader and i18nExceptionErrorFilter

---

src/services/i18n.service.ts

fix: check if the args are defined in nested translations

---

src/utils/util.ts
tests/i18n-dto.e2e.spec.ts
tests/i18n.spec.ts

proposed solution to fix #350
sanitize values in the message string from | characters

sanitize values from pipe characters

---

src/filters/i18n-validation-exception.filter.ts

Closes https://github.com/toonvanstrijp/nestjs-i18n/issues/348

fix: filter support for graphql

---

src/services/i18n.service.ts
tests/i18n.spec.ts

- added new method I18nService.getTranslations
- implemented corresponding tests cases

Add I18nService.getTranslations method

---

src/services/i18n.service.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts

follow up https://github.com/toonvanstrijp/nestjs-i18n/pull/369#issuecomment-1188847837

fix(i18n-service): remove args default value

---

docs/guides/fallback-languages.md
src/services/i18n.service.ts

expose handleFallbacks as resolveLanguage

---

docs/guides/array.md
docs/guides/debugging.md
docs/guides/exception-filters.md
docs/guides/fallback-languages.md
docs/guides/graphql.md
docs/guides/grpc.md
docs/guides/guard.md
docs/guides/mailer.md

Feat: implements array guide

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/typo.yml
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

This adds standard issue templates for the repo

feat: add issue template

---

docs/quick-start.mdx

Fixes the readme doc for missing forRootAsync method example
#472

fix: add example for forRootAsync

---

.github/workflows/deploy-docs.yaml
docs/quick-start.mdx
samples/dto-validation/.eslintrc.js
samples/dto-validation/.gitignore
samples/dto-validation/.prettierrc
samples/dto-validation/README.md
samples/dto-validation/nest-cli.json
samples/dto-validation/package.json
samples/dto-validation/pnpm-lock.yaml
samples/dto-validation/src/app.controller.ts
samples/dto-validation/src/app.module.ts
samples/dto-validation/src/app.service.ts
samples/dto-validation/src/dtos/create-user.dto.ts
samples/dto-validation/src/i18n/en/test.json
samples/dto-validation/src/i18n/en/validation.json
samples/dto-validation/src/i18n/nl/test.json
samples/dto-validation/src/i18n/nl/validation.json
samples/dto-validation/src/main.ts
samples/dto-validation/tsconfig.build.json
samples/dto-validation/tsconfig.json

Add sample apps for common use cases for the lib
none

chores: add sample folder for common examples

---

docs/guides/dto_validation/global-validation.md
docs/quick-start.mdx
package-lock.json
samples/dto-validation/src/app.service.ts
samples/simple/.eslintrc.js
samples/simple/.gitignore
samples/simple/.prettierrc
samples/simple/README.md
samples/simple/nest-cli.json
samples/simple/package.json
samples/simple/pnpm-lock.yaml
samples/simple/src/app.controller.ts
samples/simple/src/app.module.ts
samples/simple/src/app.service.ts
samples/simple/src/i18n/en/test.json
samples/simple/src/i18n/en/validation.json
samples/simple/src/i18n/nl/test.json
samples/simple/src/i18n/nl/validation.json
samples/simple/src/main.ts
samples/simple/tsconfig.build.json
samples/simple/tsconfig.json

fix: add examples

---

package-lock.json
package.json
src/loaders/i18n.json.loader.ts
src/loaders/i18n.yaml.loader.ts

Add a basic error handler when i18n file parsing fails
https://github.com/toonvanstrijp/nestjs-i18n/issues/457
yaml and json parser

fix: add error handler for i18n file parsing

---

src/interfaces/i18n-validation-error.interface.ts
src/pipes/i18n-validation.pipe.ts
src/utils/util.ts

Added errorHttpStatusCode to the I18nException

---

package.json

Add keywords and version bumps for next release

fix: add keywords and version bump

---

src/pipes/i18n-validation.pipe.ts
src/utils/util.ts

This fixes the signature for i18nErrorFactory with nestjs  errorfactory

fix: match i18nValidationErrorFactory signature with nestjs errorFactory

---

docs/quick-start.mdx
package.json
src/i18n.module.ts
src/interfaces/i18n-options.interface.ts
src/services/i18n.service.ts
src/utils/util.ts

Adds an option to throw an error on translation missing
closes https://github.com/toonvanstrijp/nestjs-i18n/issues/557

feat: option to throw on translation missing

---

package.json
src/index.ts
src/interceptors/i18n-language.interceptor.ts
src/utils/index.ts

Better typing with `i18ntranslation` type
Also fixes some small imports

feat: add i18ntranslation type and import fixes

---

docs/faq/common.md

doc: add nested translation faq

---

src/i18n.module.ts

Removes the usage of chalk. Fixes https://github.com/toonvanstrijp/nestjs-i18n/issues/574

fix: remove chalk as its barely used

---

tsconfig.json

closes https://github.com/toonvanstrijp/nestjs-i18n/issues/587

Update tsconfig.json to use lf

---

src/utils/typescript.ts

This PR sets the line ending for the printer explicitly, so that we get consistent line endings on all plattforms.
Fixes #587

Get platform independent line style

---

package.json

chores: version update

---

package.json

feat: version bump

---

src/i18n.context.ts
src/interceptors/i18n-language.interceptor.ts
src/middlewares/i18n.middleware.ts
src/utils/context.ts

fixes https://github.com/toonvanstrijp/nestjs-i18n/issues/479 , https://github.com/toonvanstrijp/nestjs-i18n/issues/619

feat: logging control for unsupported context

---

package.json

chores: version bump

---

package.json
src/services/i18n.service.ts

fix: dont log for throwOnError when disabled

---

src/utils/util.ts

This PR fixes formatI18nErrors function to work property when `target` property not exists on `error` object.
#659

Fixes #659 :bug: fix formatI18nErrors function to work property when 'target' property not exists on 'error' object

---

src/i18n.module.ts

Adds info for generated message for formatter and linter

fix: change the generated message to be more concise

---

docs/guides/dto_validation/global-validation.md

I just cleared docs. Because of current docs, I spend about 4 hour to fix problem with dto validation. Finally i saw example code and everything solved.

fix and clear docs for dto validation

---

package-lock.json
package.json

Update Dependencies to  stop security alerts
https://github.com/toonvanstrijp/nestjs-i18n/issues/668

Fixes #668: Update Dependencies - security alerts
