lib/i18n.module.ts
lib/utils/parse.ts
tests/i18n-async.spec.ts
tests/i18n.spec.ts

This PR adds a trailing slash to the `parse()` method when loading the translations. In the current state, the translations cannot be loaded if you pass a path **without** trailing slashes.

Add Trailing Slash to Path

---

README.md
lib/i18n.module.ts
lib/interfaces/i18n-options.interface.ts
lib/utils/parse.ts
tests/i18n.spec.ts
tests/i18n/en/test.custom

This PR adds the feature to define a file-pattern (i.e., the currently hard-coded `*.json`) when loading translation files.
In particular, it does:
- add "default i18noptions"
- add possibility to change the file-pattern for loading files
- added tests
- update readme file
feedback is appreciated

File Patterns

---

lib/services/i18n.service.ts
package-lock.json
tests/i18n.spec.ts

This fixes a bug where a user might be requesting a string for a language that is not registered, but there's a fallback option available.
Thank you so much!

Use fallback language if a string is requested for a non supported language

---

lib/index.ts

This PR exports the (currently missing) `header.resolver`.

fix: export header resolver

---

README.md
lib/i18n.module.ts
lib/interfaces/i18n-options.interface.ts
lib/middleware/i18n-language-middleware.ts
lib/services/i18n.service.ts
package-lock.json
package.json
tests/i18n-missing.spec.ts

This feature adds a new `saveMissing` flag to the options.
This flag, in turn, describes, if MISSING translations should automatically be saved to a  `json.missing` file in the respective `language` folder (e.g., `i18n/en`).
If you call
```ts 
i18n.translate('some.missing.key', { lang: 'en' });
```
a new `json.missing` file will be created with the following content:
```json
{
"some": {
"missing": {
"key": ""
}
}
}
```
unfortunately i had to include `lodash` for this :(

feat: add missing keys

---

package-lock.json
package.json
src/lib/decorators/i18n-lang.decorator.ts
tests/app/cats/cat.model.ts
tests/app/cats/cat.module.ts
tests/app/cats/cat.resolver.ts
tests/app/cats/cat.service.ts
tests/app/cats/cat.types.graphql
tests/app/controllers/hello.controller.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n-gql.e2e.spec.ts
tests/i18n/en/test.json
tests/i18n/nl/test.json

This PR is some kind of FIX.
Previously, the `@I18nLang()` decorator was not able to resolve the language when running in `GraphQl` Context. This PR adds this feature.
Most of the PR, however, is testing code :(

fix: make @I18nLang() decorator access GQL Context

---

src/lib/services/i18n.service.ts
tests/i18n.spec.ts

This PR fixes a bug in the `I18nService.translate()` method.
Based on the signature, the `options?` param is optional - however, due to the `destruct` operator in the method, it is not.
I added a "sane default" for the options (i.e., the language is set to the fallback language)
All the best

Fix: fix bug in translate() method

---

README.md
src/lib/interfaces/i18n-options.interface.ts
src/lib/services/i18n.service.ts
tests/i18n-async.spec.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n-gql.e2e.spec.ts
tests/i18n.spec.ts
tests/i18n/fr/test.json
tests/i18n/pt-BR/test.json

To configure multiple fallbacks. #138  :metal: 
Hey mate @ToonvanStrijp ! I hope I've made the proper changes to this PR. 
Btw, feel free to suggest any changes or correct my mistakes if needed =)
Cheers

added fallbacks

---

src/resolvers/header.resolver.ts

When the request includes no headers, "HeaderResolver" creates an error "Cannot read property 'xxx' of undefined", where "xxx" is the name of the expected header.

Fix an issue with the HeaderResolver when the request includes no headers.

---

src/i18n.module.ts
src/interfaces/i18n-options.interface.ts
src/services/i18n.service.ts

Context
When there is a missing translation there is an error pushed to our logger. The idea of this PR is to make this logging optional  . The idea is to add a new parameter in i18n options.
Features
- add logging parameter in the i18n options
- enable logging only if the passed parameter is true
- logging parameter is set to true by default so we can avoid breaking changes

Make error logging optional

---

src/services/i18n.service.ts

Context
When a user wants to regularly update translations with the refresh function but not update the actual files as they are probably fetched from 3rd party API he/she can pass the ready translations to the refresh function.
Features
- add languages as an optional param to refresh
- add translations as an optional param to refresh

Pass translations to refresh function as an optional parameter

---

src/i18n.module.ts

The mistake was made in order to cover the async initialize of the i18n module.
I18n options are passed differently in async and sync module init.
Tests are fixed:

fix wrong passing of i18n functions.

---

src/services/i18n.service.ts

I was trying to use the fallback mechanism for my project, but when the translation does not exist it will print an error in the console. I wanted to disable these errors, so I used  the "i18nOptions.logging" option and it works, but then the message remains untranslated. I think someone may have misplaced the bracket here, as the logging option should only disable error output.
My pull request makes it skip printing the message, when logging is disabled, and continuing to translate the message using the fallback language.

Fix translation with disabled logging

---

README.md
src/resolvers/accept-language.resolver.ts

This PR resolves an issue stated in #255. I originally wanted to add language mapping as a option to the `AcceptLanguageResolver`, but this would lead to some break changes or copy-pasting code from the `accept-language-parser` library in order to preserve consistency.
Allowing users to change language resolution will result to be able to handle situation like this:
`cs-CZ,en,*` => `cs` // 'loose' match type
`cs-CZ,en,*` => `en` // 'strict' match type
`cs-CZ,en-GB,*` => `cs` // 'strict-loose' match type
without any breaking changes.

Add matchType option to AcceptLanguageResolver

---

package-lock.json
package.json
src/i18n.module.ts
src/interfaces/i18n-options.interface.ts
src/services/i18n.service.ts

This resolves https://github.com/toonvanstrijp/nestjs-i18n/issues/271, but in a more generic way, by allowing users to supply their own formatter functions in place of the default `string-format` one.

add pluggable formatter functions

---

docs/guides/dto-validation.md
package-lock.json
src/filters/i18n-validation-exception.filter.ts
src/interfaces/i18n-validation-exception-filter.interface.ts
src/types/either.type.ts
src/types/only.type.ts
src/utils/format.ts
tests/app/controllers/hello.controller.ts
tests/app/examples/example.functions.ts
tests/i18n-dto.e2e.spec.ts

This pull request adds the possibility to format the validation error messages using a custom self-written function. This self-written function can be defined in the `I18nValidationExceptionFilter`. See the example below.
```typescript
@UseFilters(new I18nValidationExceptionFilter({
errorFormatter: (errors: ValidationError[]) : object  => {
const formattedErrors = errors;
// Custom implementation to format the errors
return formattedErrors;
}
}));
```
Although [#327](https://github.com/toonvanstrijp/nestjs-i18n/pull/327) adds the possibility to flatten the validation errors, sometimes you want full control of how the errors are formatted. For example, I like to group the errors by the error's property so I can display them under a specific input field in the frontend.
I moved the …

I18n error formatter

---

src/filters/i18n-validation-exception.filter.ts

This pull request https://github.com/toonvanstrijp/nestjs-i18n/pull/337 introduced a bug when using the latest version 9.1.0 because of some absolute paths

fix: relative path in i18n-validation-exception filter

---

src/loaders/i18n.abstract.loader.ts
src/utils/file.ts

Consider using `fs/promises` instead of the older `fs` module.
That way, we don't need to `promisify` its methods.
Documentation: https://nodejs.org/api/fs.html#promises-api

refactor(loaders): replaced `fs` module with `fs/promises`

---

docs/guides/dto-validation.md
src/filters/i18n-validation-exception.filter.ts
src/interfaces/i18n-validation-exception-filter.interface.ts
tests/app/controllers/hello.controller.ts
tests/i18n-dto.e2e.spec.ts

The `i18nValidationErrorFactory` always returns a `I18nValidationExceptionFilter` with 400 as http code.
It could be useful to change it (422 for example)

add option to change http code in I18nValidationExceptionFilter

---

src/services/i18n.service.ts

- we already have `const args = options?.args ?? {};` in line 151 so `(args || (args instanceof Array && args.length > 0)))` is always evaluated to true
- remove unnecessary extra parenthesis in while loop

refactor (i18n-service): remove unnecessary args check

---

package.json
src/services/i18n.service.ts

The library seems to leak memory due to missing unsubscribes in the i18n service.  
I am using nestjs-i18n in a [bull](https://github.com/nestjs/bull) queue task, that runs quite often and in a [separate process](https://docs.nestjs.com/techniques/queues#separate-processes). 
Since version nestjs-i18n 9.0.0 our server restarts often because we run out of memory. 
Before fix:
Before nestjs-i18n 9.0.0 version:
After fix:

Fix memory leaks

---

src/utils/util.ts

Since v9.1.7 I get a _Cannot find module 'src/services/i18n.service' or its corresponding type declarations._ error, which occurs inside `utils/util.ts`. Changing that to a relative import should fix it.

fix(util.ts): changes I18nService and TranslateOptions imports into a relative import

---

docs/concepts/resolver.md

fixed typo on resolvers options (AcceptLanguageResolver)

fix: typo on official guide

---

src/services/i18n.service.ts
tests/app/controllers/hello.controller.ts
tests/app/views/ejs/index3.ejs
tests/i18n-ejs.e2e.spec.ts

Fix "RangeError: Maximum call stack size exceeded" when trying to translate a key that doesn't exist and Nestjs-i18n tries to use an unsupported fallback language.
- [ x] Bug fix (non-breaking change which fixes an issue)
Using an invalid key for translation:
> [Nest] 20128  - 11/01/2023 07:51:52   ERROR [I18nService] Translation "route.null" in "pt-BR" does not exist.
> [Nest] 20128  - 11/01/2023 07:51:52   ERROR [I18nService] Translation "route.null" in "pt-BR" does not exist.
> [Nest] 20128  - 11/01/2023 07:51:52   ERROR [I18nService] Translation "route.null" in "pt-BR" does not exist.
> [Nest] 20128  - 11/01/2023 07:51:52   ERROR [I18nService] Translation "route.null" in "pt-BR" does not exist.
> [Nest] 20128  - 11/01/2023 07:51:52   ERROR [I18nService] Translation "route.null" in …

Fix for RangeError: Maximum call stack size exceeded

---

src/i18n.module.ts

Fixes a typo in the warning message. The warning message shows when to resolvers are defined.

fix: typo in warning message

---

docs/faq/_category_.json
docs/faq/common.md
package-lock.json

doc: add faq section

---

src/utils/context.ts

[@golevelup/nestjs](https://github.com/golevelup/nestjs) is a really powerful library when using RabbitMQ with NestJS.
It's a way more advanced library compared to `@nestjs/microservices` for RabbitMQ integration.
Currently it's not compatible with `nestjs-i18n` because it uses an `ExecutionContext` type `rmq` which is not handled by `nestjs-i18n`.
This PR aims to use the `ConsumeMessage` as container for the `i18nContext`, to enable creating custom lang resolvers for RabbitMQ consumers:
```ts
import { ExecutionContext } from '@nestjs/common';
import { I18nResolver } from 'nestjs-i18n';
export class RabbitMqHeaderResolver implements I18nResolver {
resolve(context: ExecutionContext): string | undefined {
if (context.getType<string>() === 'rmq') {
const consumeMessage = context.getArgs()[1] …
```

feat: add compatibility with @golevelup/rabbitmq

---

package-lock.json
src/interceptors/i18n-language.interceptor.ts
tests/app/controllers/hello.controller.ts
tests/app/interceptors/test.interceptor.ts
tests/i18n-disable-middleware.e2e.spec.ts

I discovered a bug when using `disableMiddleware: true`.
When relying on `I18nLanguageInterceptor` to initialize the `I18nContext`, it's not possible to use another interceptor on the same endpoint. 
When doing so, the `AsyncLocalStorage` containing the i18n context is broken: `I18nContext.current()` always returns `undefined`.
- Set `disableMiddleware: true` in `I18nModule` options.
- Define a simple interceptor such as:
```ts
@Injectable()
export class TestInterceptor implements NestInterceptor {
intercept(_: ExecutionContext, next: CallHandler): Observable<unknown> {
return next.handle();
}
}
```
- Add it on your endpoint:
```ts
@Get()
@UseInterceptors(TestInterceptor)
helloWorld() {
return I18nContext.current()?.lang;
}
```
- This endpoint will always return `undefined` instead of the …

fix: I18nContext.current() undefined when using additional interceptors

---

src/services/i18n.service.ts

As discussed here [https://github.com/toonvanstrijp/nestjs-i18n/discussions/540](https://github.com/toonvanstrijp/nestjs-i18n/discussions/540): It would be nice to only print an error to the console if the translation couldn't be found in any fallback language. Therefore I created this PR.
This will prevent "polluting" logs as the system works as intended and will only log an error if no key in any fallback language is found.
[https://github.com/toonvanstrijp/nestjs-i18n/discussions/540](https://github.com/toonvanstrijp/nestjs-i18n/discussions/540)
Following the Boy Scout rule (Always leave the code you are working on a little bit better than you found it.) I also tried to make the function I touched more readable.
This is my first contribution. Feel free to remark on anything I can …

move error log to only show if key for default value is missing

---

docs/quick-start.mdx

Fixing missing ``path.`` to the ``path.join`` of some quick-start code examples
Some code examples of the quickstart guide miss the `path.` before the join, when concatenating the current directory with the i18n module. This PR just adds those missing `path.`.

Adding some missing path. to code quick-start.mdx examples

---

docs/quick-start.mdx
src/services/i18n.service.ts
tests/app/cats/cat.resolver.ts
tests/app/cats/cat.types.graphql
tests/app/controllers/hello.controller.ts
tests/app/hero.proto
tests/app/interfaces/hero.interface.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts
tests/i18n-gql.e2e.spec.ts
tests/i18n-rpc.e2e.spec.ts

When using I18nService, if the context lang is not passed to the service options, it will always fallback to the fallback language, even though the context lang is accessible automatically in I18nService.
So in order to prevent passing the lang manually to the I18nService options, I used the `I18nContext.current().lang` which is the lang resolved by resolvers, as the primary default for the translate method inside I18nService. 
If the context current lang does not exist, it will use the fallback lang as default.

Use context lang as primary default for service

---

docs/guides/type-safety.md

On the file docs/guides/type-safety.md, I noticed a typo on line 105 where the word "craete" was used instead of "create." I have corrected this typo.

Fix: Typo in Type Safety Guide Documentation

---

src/filters/i18n-validation-exception.filter.ts
src/middlewares/i18n.middleware.ts
src/utils/typescript.ts
tests/i18n-dto.e2e.spec.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts

Closes Issue no: #646 
This PR addresses issue #646 by modifying the buildResponseBody method in the I18nValidationExceptionFilter class. The goal is to standardize the error response structure for validation errors, ensuring consistency across all exception types in NestJS.

fix(#646): I18nValidationExceptionFilter error response body

---

.github/workflows/test.yaml
package.json
src/i18n.context.ts
src/interceptors/i18n-language.interceptor.ts
src/middlewares/i18n.middleware.ts
src/services/i18n.service.ts
src/utils/context.ts
tests/app/examples/example.functions.ts
tests/i18n-dto.e2e.spec.ts
tests/i18n-ejs.e2e.spec.ts
tests/i18n-express.e2e.spec.ts
tests/i18n-fastify.e2e.spec.ts

While preparing another change, I noticed that the `lint` script doesn't work and that there formatting issues in the code.
Both could be detected if the GitHub workflow `test` would also lint & check the formatting.
This is added by this PR.
I also added a `verify` script to be able to easily execute all relevant scripts locally.
To get the build green, we also need to format the code in this PR. I'd suggest to extract these formatting changes into another PR which should be merged before this one (#670).
The current `lint` script `eslint '{src,apps,libs,test}/**/*.ts'` runs into the following error:
```
> eslint '{src,apps,libs,test}/**/*.ts'
Oops! Something went wrong! :(
ESLint: 8.49.0
No files matching the pattern "'{src,apps,libs,test}/**/*.ts'" were found.
Please check for typing …
```

build: check format & lint in GitHub workflow

---

docs/guides/view_engines/ejs.md

While reading the docs I noticed some typos in the EJS view engine section.

fix: typos in ejs.md

---

package-lock.json
src/types.ts

When a key name exists with the same name as an array method / field, that key will not be available as the generated type.
Example generated file:
```typescript
export type I18nTranslations = {
"common": {
"shift": {
"created": string;
};
};
};
export type I18nPath = Path<I18nTranslations>;
```
The type does not recognise the key `common.shift.created`.
I fixed the type by excluding array key names only when the field contains an array.
/
/

bugfix: exclude array key names only for array fields

---

docs/quick-start.mdx

Just fix the documentation because imports config module is missing forRootAsync configuration.

fix: add ConfigModule import to I18nModule setup
